### ISSUE TITLE
Events not responding to time input.

### ISSUE THREAD

**Issue by SEAWAKE** [DCSR/SA200#1]
I’ve noticed that when in the graphs tab of selfadmin, the events selection does not respond to time input. It is stuck only showing events for 180 minutes. Selecting other times (e.g. 10, 30, 60, 360) result in no change in the events graph. This is an old bug that I’m just now getting around to reporting. Not experiment crippling so it’s been low on the priority list.

**Comment by DCSR** [comment]
It should now respond to x-axis radio button choice. Let me know if it works for you.

**Comment by SEAWAKE** [comment]
The events record now responds to time input.
